### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by simondobson**
Updates to make

### CODE REVIEW

**Comment by RubenAssouline** [comment]
Hi, i have some questions about how to configure it. 
Can you explain me how can i integrate it on my website ? What is the first thing i have to do ? :) 
Thanks to help me to do it !

**Comment by RubenAssouline** [comment]
And my other question is : is there a gem you use here ? i don't see it on the gemfile ..

**Comment by simondobson** [comment]
Hey @RubenAssouline . Thanks for taking a look. I will update the project this week as it is a little outdated, I will include a better README. However to answer your question, if you use Ruby on Rails to develop your website then you can use Typeform + this tool to have a Typeform front end feed into your Rails website :D

**Comment by simondobson** [comment]
Hey @RubenAssouline I've updated the README, if you want to use it or have any questions don't hesitate to ask!

**Pull request closed without merging**
